[book]
authors = ["IY ZHang", "SR Wang"]
language = "en"
src = "src"
title = "igor group"

[output.html]
no-section-label = true
additional-css = ["theme/custom.css"]
additional-js = ["theme/language-switcher.js"]
